### ISSUE TITLE
02-PSBBN-Installer has a small syntax issue after recent changes.

### ISSUE THREAD

**Issue by Lupus-severus** [CosmicScale/PSBBN-Definitive-English-Patch#11]
Just a heads up, with the recent changes the line says TOOLKIT_PATH=$"(pwd)" and breaks the installer because it can't find the directory.

Simple fix of the double quote being on the wrong side of the $

TOOLKIT_PATH="$(pwd)"

**Comment by CosmicScale** [comment]
Thank you! It's fixed.
