### ISSUE TITLE
Games from the CD folder won't install

### ISSUE THREAD

**Issue by Tendan-F** [CosmicScale/PSBBN-Definitive-English-Patch#12]
I ran into an issue while installing games, everytime I run the `03-Game-Installer.sh` script it doesn't seem to install any of the games that are located within the `CD` folder. It copies the files to the PS2 Drive just like it does with the games located in the `DVD` and `POPS` folder but it does not look for artwork or try to install them onto the PSBBN Games Channel. It moves the files and then proceeds to install the content in the `DVD` folder.

Here are the [game-installer.log](https://github.com/user-attachments/files/18155438/game-installer.log) and [ps2.log](https://github.com/user-attachments/files/18155458/ps2.log) I got after trying to install the CD games a couple of times.
(Renamed it to `ps2.log` cause Github didn't allow me to upload it as `.list`)

And these are the CD games I was trying to install.
```
SLES_500.32 Theme Park World
SLES_512.18 Harry Potter and the Chamber of Secrets
SLES_512.57 The Sims
SLES_512.85 Spongebob SquarePants - Revenge of the Flying Dutchman
SLES_513.54 Jurassic Park Operation Genesis
```

I'm not sure if this is a user error on my part or an issue with the script so I thought I'd bring it up just in case.

(Edit: I think I may have found a cause of this, all my CD games are in `.BIN` and `.CUE` format, I assume only `.ISO` and `.ZSO` files work? since all the games in your CD folder in the video where in those formats)

**Comment by CosmicScale** [comment]
You got it, CD games need to be either `.ISO` or `.ZSO`. Glad you got it figured out.

**Comment by Tendan-F** [comment]
ah my bad man, I feel really dumb now lol. sorry for the uneasceseary issue on the git page.
