### ISSUE TITLE
Request for information on the artwork format

### ISSUE THREAD

**Issue by dsdsdsdgg** [CosmicScale/PSBBN-Definitive-English-Patch#13]
Hey CosmicScale, great work here.

Not an issue, just a request for information.

In the video you mentioned 256x256 8-bit color depth, but in /icons/art I'm seeing some 24-bit and 32-bit images. 
Would you be able to tell us more about the format the art needs to be in for PSBBN? Is transparency supported?

Thank you for your time.

**Comment by CosmicScale** [comment]
Oh, some of the unconverted files must have got mixed in by mistake. I'll take a look at that.

I haven't experimented with transparency. If you want to play around with different art, just replace images in the art folder and re-sync your games.

**Comment by CosmicScale** [comment]
> but in /icons/art I'm seeing some 24-bit and 32-bit images.

I checked all art uploaded to the repository and they are all 8-bit. Can you give me a Game ID of an effected game?

**Comment by dsdsdsdgg** [comment]
Windows is probably just being weird then. Every file I'm check reports 32-bit or 24-bit.
![image](https://github.com/user-attachments/assets/07f60ce0-7c85-4bd5-b4d5-b27afd748473)

**Comment by dsdsdsdgg** [comment]
Yeah... Photoshop reports RGB/8.
![image](https://github.com/user-attachments/assets/46f4a593-165c-4f07-a9a9-b7fc30e2d29a)
Sorry for the confusion.

**Comment by CosmicScale** [comment]
Oh, okay. They're definitely 8-bit:
`PSBBN-Definitive-English-Patch/icons/art/PBPX_955.02.png PNG 256x256 256x256+0+0 8-bit sRGB 163453B 0.000u 0:00.001`

I added a load of images the other night and you got me wondering if I forgot to convert them lol

I'll close this now.
