### ISSUE TITLE
PSBBN Not loading with the Kingston A400, sent back to original browser

### ISSUE THREAD

**Issue by Lupus-severus** [CosmicScale/PSBBN-Definitive-English-Patch#14]
I keep getting kicked back to the original browser upon trying to load PSBBN when using the A400 which I know is absurd because it's the one you recommended, nothing seems to get flagged during any of the install process and my adapter is still good because I ran FHDboot with it.

The drive is definitely getting power as I can hear it.

Any ideas?

Here's the logs:

[game-installer.log](https://github.com/user-attachments/files/18201072/game-installer.log)

[PSBBN-installer.log](https://github.com/user-attachments/files/18201073/PSBBN-installer.log)

**Comment by CosmicScale** [comment]
Can't see any issues with the install. Are you using an official Sony Network Adapter?

**Comment by Lupus-severus** [comment]
I am indeed, the Japanese SCHP-10350 one. Although I also tried to run mbr raw from the ssd and it wouldn't even load that so I'm doing a super slow format to see if that helps as the drive must be at fault here. Will keep you posted.

**Comment by Lupus-severus** [comment]
No luck, it just takes its time on the startup sequence, goes to load something and then goes back to the browser.
Is it possible it's timing out?

**Comment by CosmicScale** [comment]
I think the issue is most likely with your network adapter or the SATA mod, especially if the drive is working okay on your PC and the PSBBN installer is not showing any errors.

**Comment by Lupus-severus** [comment]
Tried the old HDD again and that booted into BBN no problem... So it's looking like the drive being incompatible either with the kaico or with bbn (both of which wouldn't make any sense as I know you've tried this drive before)

**Comment by CosmicScale** [comment]
> (both of which wouldn't make any sense as I know you've tried this drive before)

Yep, tried and tested on both the Kingston A400 240G and the Kingston A400 960G. Both work great for me with no issues. It is definitely a problem with your particular SSD. Glad you managed to get it working on a HDD.
