### ISSUE TITLE
PSBBN Installer 2TB SSD Error

### ISSUE THREAD

**Issue by joenuts690** [CosmicScale/PSBBN-Definitive-English-Patch#15]
Error: Device is 1 GB. Required minimum is 200 GB. Press any key to exit. I'm using a 2TB Samsung Evo SSD, any fixes? 
![20241219_162300](https://github.com/user-attachments/assets/0fd20dfd-3c2e-406d-8cde-394add518f1e)

**Comment by CosmicScale** [comment]
Thanks for reporting! It's fixed now with [commit 42fdc1f](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/42fdc1f189e18c0a6dbee5a9e46e325e9f4ef633)
