### ISSUE TITLE
Problems while downloading Game Arts on Xubuntu 22.04.5

### ISSUE THREAD

**Issue by GreyzardBigME** [CosmicScale/PSBBN-Definitive-English-Patch#18]
the first two scripts works fine, the third one can install games without any issue but when i try to download the game covers i get errors, with the script unable to install puppeeteer and asks me to check if npm is installed correctly (and indeed, it is) some covers are already in the corresponding folder on linux and the script use them correctly, so apparently the problem is related only to the download.
i include a .zip file with the whole content of the .npm folder, containing the logs as well.

[npm.zip](https://github.com/user-attachments/files/18219615/npm.zip)

**Comment by CosmicScale** [comment]
Your version of `node` is too old and needs updating. I'll add that to the setup script so others won't run into this issue.

```
457 warn EBADENGINE   required: { node: '>=18' },
457 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }

**Comment by CosmicScale** [comment]
I have just checked the setup script and it already updates and installs nodejs. No idea why this is not the case on Xubuntu. You will have to update manually.

**Comment by GreyzardBigME** [comment]
i tried because i wanted to use the Xubuntu virtual machine without making anoter one dedicated to Mint, but in the end i preferred to make it aniway (i installed the main Cinnamon version), now i get the errors listed in the attached .txt file
[Errors.txt](https://github.com/user-attachments/files/18233615/Errors.txt)

**Comment by GreyzardBigME** [comment]
i tried because i wanted to use the Xubuntu virtual machine i already have without making anoter one dedicated to Mint, but in the end i preferred to make it aniway (i installed the main Cinnamon version), now i get the errors listed in the attached .txt file
[Errors.txt](https://github.com/user-attachments/files/18233621/Errors.txt)

**Comment by CosmicScale** [comment]
I’m sorry, but I’m unable to assist you further with this issue. It seems there’s a problem with your virtual machine setup. This issue appears to be unique to your environment, as no other users have reported problems with the art downloader.

These scripts were developed and thoroughly tested on Linux Mint 22 (64-bit Cinnamon Edition). They work flawlessly on both a native installation and a Live USB setup. I recommend trying to run the scripts in one of these configurations for the best results.

**Comment by GreyzardBigME** [comment]
Even a live session (both at boot and virtual box) gives me the same errors, do you know some "ultimate archive" where I can manually download the arts? And/or how to convert images? Because, as mentioned before, if the arts are already in the internal folder they're applied correctly, i even changed the ID of some images to match my (mostly) PAL games (for example, Final Fantasy X and X-2, also the Kingdom Hearts and Ratchet and clank series), so the missing arts list shrinked

**Comment by GreyzardBigME** [comment]
Even a live session (both at boot and virtual box) gives me the same errors, do you know some "ultimate archive" where I can manually download the arts? And/or how to convert images? Because, as mentioned before, if the arts are already in the internal folder they're applied correctly, i even changed the ID of some images to match my (mostly) PAL games (for example, Final Fantasy X and X-2, also the Kingdom Hearts and Ratchet and clank series), so the missing arts list shrinked

Is it possible to make a Raspberry Pi version of the scripts?

**Comment by CosmicScale** [comment]
You can manually download all the images from IGN. There should be a tmp folder in the art folder. If you place your own images in the tmp folder with filenames that match your games id, they will be converted and installed next time you run the game installer script.

Raspberry Pi OS is based on Debian so the scripts will most likely work but I haven't tested this. This issue is now closed.
