### ISSUE TITLE
PSBBN install won't verify 

### ISSUE THREAD

**Issue by chilloutsessions** [CosmicScale/PSBBN-Definitive-English-Patch#2]
Verifying installation...
/home/user/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 1: �: not found
/home/user/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 1: ELF: not found
/home/user/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 2: 0: not found
/home/user/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 3: Syntax error: word unexpected (expecting ")")
Error: Verification failed on /dev/sdb.

**Comment by chilloutsessions** [comment]
[PSBBN-installer.log](https://github.com/user-attachments/files/18140635/PSBBN-installer.log)

/home/williamyoul/PSBBN-Definitive-English-Patch/helper

**Comment by CosmicScale** [comment]
I'm really baffled because you're the only one having this issue. Make sure `HDL Dump.elf` is executable. Try running:

`sudo /home/williamyoul/PSBBN-Definitive-English-Patch/helper/HDL\ Dump.elf toc /dev/sdb`

**Comment by chilloutsessions** [comment]
Very weird , the files there but it's not recognised.



sudo /home/williamyoul/PSBBN-Definitive-English-Patch/helper/HDL\ Dump.elf toc /dev/sdb
[sudo] password for williamyoul: 
/home/williamyoul/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 1: �: not found
/home/williamyoul/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 1: ELF: not found
/home/williamyoul/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 2: 0: not found
/home/williamyoul/PSBBN-Definitive-English-Patch/helper/HDL Dump.elf: 3: Syntax error: word unexpected (expecting ")")
![Screenshot from 2024-12-16 19-10-00](https://github.com/user-attachments/assets/d9ff257f-74f2-4958-a51e-05a3f53b6e3c)

**Comment by CosmicScale** [comment]
This sounds like a permissions issue to me. Are the files definitely executable?

This problem seems to be isolated to your setup. At this point I recommend making a Linux Mint bootable USB drive and running it from there.

**Comment by chilloutsessions** [comment]
![Screenshot_2024-12-17_21-49-19](https://github.com/user-attachments/assets/788c3301-aaa4-4d7f-836a-b2fb13ffd902)

Now using mint linux, it believes I have no internet connection, even though I do. 
It even let me manually download the file from archive.

Is there anyway to make it recognize this in the assets folder?

/home/oem/PSBBN-Definitive-English-Patch/assets/psbbn-definitive-image-v2.0.gz


I did drop internet connection also at one point , could this have caused this?

**Comment by CosmicScale** [comment]
If you run the script again the download should resume from where it left off. If you download manually, you can just put the image in the `assets` directory. The script should then skip the download completely. If you are going to go the manual route, delete any `.st` files you might have it your `assets` directory before running the script.

**Comment by chilloutsessions** [comment]
![Screenshot_2024-12-18_02-20-12](https://github.com/user-attachments/assets/b9ab4139-0db8-49b4-aae9-694f1370f198)

Managed to run the script again and it downloaded in its full file size then it said failed?
Note the asset folder created outside of the PSBBN directory.

**Comment by CosmicScale** [comment]
That shouldn't happen. How are you running the script? If you're running it from the command line, you need to `cd` into the directory with the scripts first.

**Comment by CosmicScale** [comment]
I've improved error handling and verification for the PSBBN Installer script. Before trying again, `cd` into the directory with the scripts and run `git pull`

**Comment by chilloutsessions** [comment]
Ok this is now rectified and working.

- I’m going to make an assumption that not using CD to the directory in both Ubuntu and Mint Linux may have been the cause.

I am at the stage of loading games. 

Thank you for all your help.

**Comment by CosmicScale** [comment]
Glad you got it working! I've added a check to the installer script that makes sure the user is in the correct directory before proceeding.
