### ISSUE TITLE
Unable to change screen aspect ratio/size from 4:3

### ISSUE THREAD

**Issue by gdau** [CosmicScale/PSBBN-Definitive-English-Patch#20]
Hi!

This is working great for me with about 350 games but I have a small issue - I am playing it on a modern screen with a retrotink 4k connected with component cables and in the settings of PSBBN (where you can choose the RGB/Component output) there is a select for aspect ratio/screen size - but mine seems to be stuck on 4:3 (when I select it, it doesn't seem to do anything like offer any other options). 

In both plain OPL and in the "standard" unmodded PS2 settings, I was able to change this to 16:9 - is this not supported in PSBBN or is there some other trick I'm missing?

Thank you!

**Comment by CosmicScale** [comment]
It's something that Sony never implemented in PSBBN for some reason. It wasn't a particularly useful feature anyway. You can still change the widescreen settings in OPL and individually for games that support it but the PSBBN menus will always be in 4:3
