### ISSUE TITLE
Typos/Translation errors

### ISSUE THREAD

**Issue by AkikoKumagara** [CosmicScale/PSBBN-Definitive-English-Patch#21]
In the "Game Channel", the "BANDAI Entertainment World" title is misspelled as "BANDIA Entertainment World".

![image](https://github.com/user-attachments/assets/a76f22c7-3e03-4d1e-b3f9-c1890393de37)

Inside the "PlayStation Now!" channel in the "Game Channel" area, when viewing game details for any specific title in `Software`, the word title is mistranslated as "taitle".

![image](https://github.com/user-attachments/assets/9fdd57e9-bed0-4d9f-bf7a-41cc4d49c766)

**Comment by CosmicScale** [comment]
The menu I can fix. The misspelling in the PS Now channel is from the original Japanese version and is unfortunately located in an encrypted file that cannot be modified. 

For information, I am not responsible for maintaining or translating the online channels, although I have helped to retranslate a couple.

Please only report problems with the PSBBN installer and game installer here. Thanks.
