### ISSUE TITLE
Arts Not Found

### ISSUE THREAD

**Issue by Sanjuro757** [CosmicScale/PSBBN-Definitive-English-Patch#23]
Hi I thought I would submit art issues here like you suggested your recent PSBBN 2.0 video.  I deleted my previous troubleshooting-related comments on the video. I put my toe in the Linux pond for the first time with this because I was so excited, causing me some learning pains, but I have everything working now. This is also my first post on a GitHub ever, that's how pumped this project made me!

Regarding artwork, I installed PSBBN w/ about 65 PS2 games and maybe a dozen PSX games. Of these, most worked, but there were a few that did not.

PS2 Games that did not find artwork:
The Punisher (SLUS_208.64)
Virtua Fighter 4: Evolution (SLUS_206.16)
Rule of Rose (SLUS_214.48)
Rogue Galaxy (SCUS_974.90)
Star Wars Battlefront 2 (SLUS_212.40) (It used incorrect artwork from the game Jedi Survivor)

PSX Games that did not find artwork:
Suikoden (SLUS_002.92)
Suikoden II (SLUS_009.58)
note: the ps1.list file that was generated by the script has the Game ID missing for just these two games so that may have something to do with it.

Keep up all the awesome work!

**Comment by CosmicScale** [comment]
Thanks for the report. The PS2 artwork issue has been fixed. Simply run `git pull`, then re-sync your games.

A small number of PS1 games store their Game IDs in a non-standard way so the IDs cannot be retrieved. For these games, rename the VCD files so that they begin with the game's Game ID, then re-sync.

**Comment by Sanjuro757** [comment]
> Thanks for the report. The PS2 artwork issue has been fixed. Simply run `git pull`, then re-sync your games.
> 
> A small number of PS1 games store their Game IDs in a non-standard way so the IDs cannot be retrieved. For these games, rename the VCD files so that they begin with the game's Game ID, then re-sync.

Could you be a bit more specific about 'git pull', I am very new to Linux. Thanks. (Do you just mean, download a fresh copy of the scripts from the GitHub?)
I'm assuming the Game ID for the PSX issue should be formatted like SLUS_002.92.Suikoden.VCD

**Comment by CosmicScale** [comment]
> Do you just mean, download a fresh copy of the scripts from the GitHub?

No probs. Yep, that's what `git pull` does. Open a terminal and type the following commands:
```
cd PSBBN-Definitive-English-Patch
git pull
```
You can then run the game installer script as normal.

> formatted like SLUS_002.92.Suikoden.VCD

Yep, that's right.

**Comment by Sanjuro757** [comment]
> > Do you just mean, download a fresh copy of the scripts from the GitHub?
> 
> No probs. Yep, that's what `git pull` does. Open a terminal and type the following commands:
> 
> ```
> cd PSBBN-Definitive-English-Patch
> git pull
> ```
> 
> You can then run the game installer script as normal.
> 
> > formatted like SLUS_002.92.Suikoden.VCD
> 
> Yep, that's right.

Got it, thanks! I probably should have formatted the PSX file names like this in the first place, but that is what I get for being lazy lol. I'll try to update my SSD tonight. I feel like you came outta nowhere and catapulted OPL users into the future; this feels like such a leap forward!
