### ISSUE TITLE
Error: Some partitions are missing on /dev/sda

### ISSUE THREAD

**Issue by Dereksonic01** [CosmicScale/PSBBN-Definitive-English-Patch#25]
This happens during "Running APA-Jail by Berion...". I tried twice and the issue still happened. I'm using a 500gb TOSHIBA MQ01ACF050. And running Linux Mint on a Steam Deck from SD card. Even so after the error, running the HDD on the console just hangs on a PlayStation 2 logo during startup.

**Comment by CosmicScale** [comment]
If you give me the logs I will take a look but this sounds like a hardware issue.

>console just hangs on a PlayStation 2 logo during startup

Are you using an Official Sony Network Adapter?

**Comment by Dereksonic01** [comment]
I'm using a Kaico SATA adapter. How do I get the logs?

**Comment by CosmicScale** [comment]
You need to use an Official Sony Network Adapter with a SATA mod. Third-part adapter are not supported and will case PSBBN to freeze at the PlayStation 2 logo as you described.

**Comment by CosmicScale** [comment]
Are you creating less than 100 game partitions when you get the "Some partitions are missing" error?

**Comment by CosmicScale** [comment]
"Some partitions are missing" error fixed with [commit b2fa838](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/b2fa838cef115ef0d6b2123af56aa77597f54b81)

Console freezes at PlayStation 2 logo if you are not using an official Sony Network Adapter.
