### ISSUE TITLE
PSX Art Missing for Games: Gaiaseed, Asuka 120%, and Chrono Trigger

### ISSUE THREAD

**Issue by Sanjuro757** [CosmicScale/PSBBN-Definitive-English-Patch#27]
Game IDs were appended to filenames, but art was not found or downloaded for the following games:

SLPS_006.24.Gaiaseed - Project Seed Trap.VCD
SLPS_020.74.Asuka 120% Final: Burning Fest. Final.VCD
SLUS_013.63.Final Fantasy Chronic;es: Chrono Trigger.VCD

**Comment by CosmicScale** [comment]
Fixed with [commit 29d99c8](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/29d99c85d5f00d01b0431d77a070fb1b5463b70e)
