### ISSUE TITLE
Xenosaga PS2 Games and PSX Pandamonium Games In Wrong Order

### ISSUE THREAD

**Issue by Sanjuro757** [CosmicScale/PSBBN-Definitive-English-Patch#28]
Not a big deal, but I wanted to point out that when scrolling left through the PSBBN game channel 'collection' carousel, the first game is Xenosaga Episode II (comprised of SLUS_208.92 for disc 1 and SLUS_211.33 for disc 2), followed by Xenosaga Episode III (comprised of SLUS_213.89 for disc 1 and SLUS_214.17 for disc 2), then finally Xenosaga Episode I (one disc game: SLUS_204.69).

Also, for PSX Pandemonium! (SLUS_002.32) and its sequel Pandemonium 2 (SLUS_005.78) are in reverse order.  

This doesn't bother me much, but I thought I remembered in the video, that the script attempts series-specific ordering.

**Comment by CosmicScale** [comment]
Thanks for reporting this. Fixed in [commit 64e6202](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/64e62020915d7acf9d813b78c0ad9c1cceb08a0b). Updated sorting logic to remove special characters from game titles and correct handling of Roman numeral 'I'
