### ISSUE TITLE
How do partition number / size works?

### ISSUE THREAD

**Issue by NewProject64** [CosmicScale/PSBBN-Definitive-English-Patch#31]
Hello there! Iam new to PSBBN and linux OS but after watching your video I decided to give it a try. Iam using a 240GB SSD (MSI Spatium S270) and Iam trying to use all the space available since linux tells me my drive only have 223GB to use. I would like to install 54 PS2 games (7 CD / 47 DVD) and 24 PS1 games (31 discs). All together they will use 210GB from my SSD + 10GB for the music thing, it will leave me with a couple GBs left for the PSBBN files / covers / settings / etc. (dont know how much it requires but I think its enough?). Since I will install less than 100 games, creating 100 partitions seems to be the best, less partitions means faster loading time. The thing is: the less partitions I choose, the larger will be the POPS partition, and I only need 19GB for that one. Only by choosing 625 partitions I get to have 19GB for POPS. Do you have any ideas / recommendations / solutions? Thx in advance!

ps:
- Ive tried to use both 100 and 625 partitions. I only got 22 DVDs installed on both tries because I run out of space.
- My OPL partition only have 100GB, this might be the issue.

[game-installer.log](https://github.com/user-attachments/files/18272222/game-installer.log)
[PSBBN-installer.log](https://github.com/user-attachments/files/18272223/PSBBN-installer.log)
[missing-art.log](https://github.com/user-attachments/files/18272227/missing-art.log)

**Comment by CosmicScale** [comment]
The first 128 GB of the drive is reserved for PSBBN. This space contains the operating system, OPL Launcher partitions, POPS partition, and music partition. All remaining free space on the drive is formatted as exFAT and used for PS2 games.

Partitioning the first 128 GB differently will not increase the available space for PS2 games. The solution is to use a larger drive. I recommend a drive with at least 500 GB of capacity.
