### ISSUE TITLE
Error During Setup Script

### ISSUE THREAD

**Issue by pmp174** [CosmicScale/PSBBN-Definitive-English-Patch#8]
Hi I keep getting the following error with the setup script

Press any key to continue...
Ign:1 cdrom://Linux Mint 22 _Wilma_ - Release amd64 20240721 noble InRelease
Err:2 cdrom://Linux Mint 22 _Wilma_ - Release amd64 20240721 noble Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Ign:3 http://packages.linuxmint.com wilma InRelease                                                
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease                                   
Hit:5 http://packages.linuxmint.com wilma Release                           
Hit:6 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:7 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done
E: The repository 'cdrom://Linux Mint 22 _Wilma_ - Release amd64 20240721 noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Error: Package installation failed.
Press any key to exit...

**Comment by CosmicScale** [comment]
See readme:

```
If you are installing from a Linux live USB, you must edit /etc/apt/sources.list to remove the line starting with deb cdrom before running 01-Setup.sh.
```

**Comment by pmp174** [comment]
Thank You! Btw I recommend adding to the readme. 

To edit source list type this command

$ sudo nano /etc/apt/sources.list

Using the arrow buttons navigate to the line that starts with deb cdrom and delete it.

Press Ctrl+x and then y to save changes and exit.
