### ISSUE TITLE
Feature Request PSBBN Installer partition remaining storage verification

### ISSUE THREAD

**Issue by pmp174** [CosmicScale/PSBBN-Definitive-English-Patch#9]
This is great work btw. Please add a confirmation prompt in the script letting the user know how many OPL partitions they are making and how much storage will be left for Music and POPs.

EG : Are you sure you want to create [number of partions]? You will have [space left] gb remaining for Music and POPs. Y/N

**Comment by CosmicScale** [comment]
Good idea! I'll definitely be adding that.

**Comment by CosmicScale** [comment]
Added in [commit 0b6bdf5](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/0b6bdf57389c01903c0dc43010e67dbfd7bb3891)

Thanks for the suggestion!
